
CREATE TABLE MEMBER(
	MID VARCHAR(40) PRIMARY KEY,
	MPW VARCHAR(30) NOT NULL,
	MNAME VARCHAR(50) NOT NULL,
	MPOINT INT DEFAULT 3000,
	MRANK INT DEFAULT 0
);

CREATE TABLE COFFEE(
	CID INT PRIMARY KEY,
	CNAME VARCHAR(300) NOT NULL,
	CCOUNTRY VARCHAR(100) NOT NULL,
	CNUM INT DEFAULT 0,
	CPRICE INT NOT NULL,
	CCONTENT VARCHAR(300),
	CPIC VARCHAR(500)
);

CREATE TABLE SUBSCRIBE(
	SID INT PRIMARY KEY,
	MID VARCHAR(30) NOT NULL,
	CONSTRAINT MEMFK FOREIGN KEY (MID) REFERENCES MEMBER (MID) ON DELETE CASCADE,
	CID INT NOT NULL,
	CONSTRAINT COFK FOREIGN KEY (CID) REFERENCES COFFEE (CID) ON DELETE CASCADE
);
--SELECT
SELECT * FROM MEMBER;
SELECT * FROM COFFEE;
SELECT * FROM SUBSCRIBE;
SELECT * FROM COFFEE ORDER BY CID DESC;

--DROP
DROP TABLE MEMBER;
DROP TABLE COFFEE;
DROP TABLE SUBSCRIBE;

--INSERT MEMBER
INSERT INTO MEMBER VALUES ('ADMIN','1234','작은티모',0,1);
INSERT INTO MEMBER (MID,MPW,MNAME,MPOINT) VALUES ('admin','1234','적당한티모',10000000);
INSERT INTO MEMBER VALUES ('USER','1234','큰티모',0,0);
INSERT INTO MEMBER (MID,MPW,MNAME,MPOINT) VALUES ('ADMIN1','1234','작은티모',-1);

--INSERT COFFEE
--INSERT SUBSCRIBE

SELECT A.CID, A.CNAME, A.CCOUNTRY,A.CNUM,A.CPRICE,A.CCONTENT,A.CPIC FROM COFFEE A, SUBSCRIBE B WHERE A.CID = B.CID AND B.MID = 'admin';
SELECT * FROM (SELECT ROWNUM AS RNUM, A.* FROM COFFEE A) WHERE RNUM BETWEEN 0 AND 7;
SELECT count(*) as listCnt FROM COFFEE;
SELECT * FROM (SELECT ROWNUM AS RNUM, A.* FROM COFFEE A)  WHERE CPRICE>=1000 AND CPRICE<=10000 AND RNUM BETWEEN 0 AND 6 ORDER BY CPRICE DESC;


--ROWNUM= 결과물에 순차적인 번호
--rownum 은 order by 가 이루어지기 전에 이루어진다
SELECT ROWNUM AS RNUM, CNAME, CPRICE FROM COFFEE ORDER BY CPRICE;
 
--where조건 다음에 rownum이 할당되기때문에 rownum을 where조건에서 사용할 수 없다.
SELECT ROWNUM AS RNUM, A.* FROM 
		(SELECT CNAME, CPRICE FROM COFFEE WHERE CNAME LIKE '%에%' ORDER by CPRICE desc) A;
        WHERE ROWNUM--between 1 and 17;    

SELECT ROWNUM AS RNUM, A.* FROM 
		(SELECT CNAME, CPRICE FROM COFFEE ORDER BY CPRICE DESC) A
		 WHERE ROWNUM BETWEEN 1 AND 5;

SELECT * FROM (SELECT a.*, rownum RNUM FROM
(SELECT * FROM COFFEE WHERE CNAME LIKE '%에%' ORDER by CPRICE desc)
			 A ) WHERE RNUM between 1 and 17;

SELECT ROWNUM AS RNUM, A.* FROM 
		(SELECT CNAME, CPRICE FROM COFFEE ORDER BY CPRICE DESC) A
		 WHERE ROWNUM BETWEEN 12 AND 17;
			 
SELECT * FROM 
	(SELECT ROWNUM RNUM, A.*FROM
	(SELECT CNAME, CPRICE FROM COFFEE ORDER BY CPRICE DESC)
			 A WHERE ROWNUM<=5)X WHERE X.RNUM >=1;

SELECT * FROM (SELECT ROWNUM RNUM, A.* FROM
(SELECT CNAME, CPRICE FROM COFFEE WHERE CNAME LIKE '%에%' ORDER BY CPRICE DESC)
			 A WHERE ROWNUM<=5)X WHERE X.RNUM >=1;
	
			 
			 
SELECT * FROM (SELECT ROWNUM AS RNUM, A.* FROM (SELECT * FROM COFFEE A ORDER BY CID DESC)A)
			 WHERE RNUM BETWEEN  1  AND 6;
 SELECT ROWNUM AS RNUM, A.* FROM COFFEE A ORDER BY RNUM DESC;

